### ISSUE TITLE
LMOV encoder assert bugs

### ISSUE THREAD

**Issue by Boolsheet** [Textmode/TMVM#27]
The error message of the first assert is wrong. And not all parameters are checked.

<code>asm.lua:127
assert(a and b and c, "SRE must be properly qualified: 'SRE R1,R2,RET'")</code>

And I think the last assert has it reversed. LMOV works only with address registers.

<code>asm.lua:135
assert(aa and ba and ca and da, "LMOV only works with absolute registers")</code>

**Comment by Textmode** [comment]
Two issues, the first (incorrect error message) has been corrected.
The second is actually correct (its Direct Vs. Indirect, not Value Vs. Address), and thus wontfix.
