### ISSUE TITLE
BYTE encoder errors on literals while patching

### ISSUE THREAD

**Issue by Boolsheet** [Textmode/TMVM#28]
This assert should also accept literals I think.

<code>asm.lua:428
assert(af=='symbol' and bf=='symbol', "Values may only be stored in valid, unused, symbols")</code>

**Comment by Textmode** [comment]
Clarified on IRC as issue involving patching with the BYTE encoder. will probably have to wait until the ASM parser rewrite.

**Comment by Textmode** [comment]
various fixes to asm, closed by 7ec214d9ad90cae23a1a8d6b402467b06c8fcc5f
